config/routes.rb
Rails.application.routes.draw do
  root "publications#index"

  get "/articles", to: "articles#index"
  get "/articles/:id", to: "articles#show"

  resources :publications do
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :publication
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end
  

app/models/product.rb
class Product < ApplicationRecord
  self.table_name = "my_products"
  self.primary_key = "product_id"
end

app/models/publication.rb
class Publication < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find params[:id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  
  def create
    @publication = Publication.find(params[:publication_id])
    @comment = @publication.comments.create(comment_params)
    redirect_to publication_path(@publication)
  end

  def destroy
    @publication = Publication.find(params[:publication_id])
    @comment = @publication.comments.find(params[:id])
    @comment.destroy
    redirect_to publication_path(@publication)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @publications = Publication.all
  end

  def show 
    @publication = Publication.find params[:id]
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication = Publication.new(publication_params)

    if @publication.save
      redirect_to @publication
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @publication = Publication.find(params[:id])
  end

  def update
    @publication = Publication.find(params[:id])

    if @publication.update(publication_params)
      redirect_to @publication
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    redirect_to root_path
  end

  private
    def publication_params
      params.require(:publication).permit(:title, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <a href="/articles/<%= article.id %>">
        <%= article.title %>
      </a>
    </li>
  <% end %>
</ul>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

app/views/comments/_comment.html.erb
<% unless @publication.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<p>
  <%= link_to 'Destroy Comment', [comment.publication, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @publication, @publication.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with model: publication do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% publication.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% publication.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Edit Publication</h1>

<%= render "form", publication: @publication %>

app/views/publications/index.html.erb
<h1>Publications</h1>

Our blog has **<%= Publication.public_count%>** articles and counting!
<ul>
  <% @publications.each do |publication| %>
    <% unless publication.archived? %>
      <li>
        <%= link_to publication.title, publication %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Publication", new_publication_path %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render "form", publication: @publication %>

app/views/publications/show.html.erb
<h1><%= @publication.title %></h1>

<p><%= @publication.body %></p>

<ul>
  <li><%= link_to "Edit", edit_publication_path(@publication) %></li>
  <li><%= link_to "Destroy", publication_path(@publication),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Comments</h2>
<%= render @publication.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form"%>